(module
  (memory 256 256)
  (type $0 (func))
  (type $1 (func (result i32)))
  (type $2 (func (result i64)))
  (type $3 (func (result f32)))
  (type $4 (func (result f64)))
  (type $5 (func (result v128)))
  (type $6 (func (param i32) (result i32)))
  (export "a" (func $a))
  (export "b" (func $b))
  (export "c" (func $c))
  (export "d" (func $d))
  (export "e" (func $e))
  (export "f" (func $f))
  (export "g" (func $g))
  (export "h" (func $h))
  (func $a (type $0)
    (nop)
  )
  (func $b (type $1)
    (return
      (i32.const 1337)
    )
  )
  (func $c (type $2)
    (return
      (i64.const 1337)
    )
  )
  (func $d (type $3)
    (return
      (f32.const 1337)
    )
  )
  (func $e (type $4)
    (return
      (f64.const 1337)
    )
  )
  (func $f (type $6)
    (return
      (i32.const 1337)
    )
  )
  (func $g (type $2)
    (drop
      (call $unexported_func)
    )
    (return
      (i64.const 1337)
    )
  )
  (func $unexported_func (type $2)
    (return
      (i64.const 1337)
    )
  )
  (func $h (type $5)
    (return
      (v128.const i32x4 1 3 3 7)
    )
  )
)
